name: Node.js CI/CD

on: 
    push:
      branches:
        - main
        - dev
        - '**'
      tags:
        - 'v*'
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20,18]
        steps:
            - name: Ceckout code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
